### ISSUE TITLE
downloading errors

### ISSUE THREAD

**Issue by LuMitchell** [MdSauravChowdhury/Google-artsandculture-image-downlaod#1]
$ python tile_fetch.py --zoom 4 "https://artsandculture.google.com/asset/the-water-carrier-la-aguadora/UwE2fGsMlWHuMg"
Downloading image meta-information...
Downloading tiles...
Traceback (most recent call last):
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1021, in create_connection
    raise exceptions[0]
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 1006, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 920, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\proactor_events.py", line 702, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\windows_events.py", line 595, in finish_connect
    ov.getresult()
OSError: [WinError 121] ▒źŵƳ▒ʱʱ▒▒▒ѵ▒

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Downloads\Google-artsandculture-image-downlaod-master\Google-artsandculture-image-downlaod-master\async_tile_fetcher.py", line 8, in modified
    return await f(*args, **kwargs)
  File "D:\Downloads\Google-artsandculture-image-downlaod-master\Google-artsandculture-image-downlaod-master\async_tile_fetcher.py", line 22, in fetch
    async with session.get(url) as response:
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiohttp\connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host lh3.googleusercontent.com:443 ssl:default [▒źŵƳ▒ʱʱ▒▒▒ѵ▒]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tile_fetch.py", line 181, in <module>
    main()
  File "tile_fetch.py", line 177, in main
    loop.run_until_complete(coro)
  File "C:\Users\xx\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "tile_fetch.py", line 131, in load_tiles
    tiles = await async_tile_fetcher.gather_progress(awaitable_tiles)
  File "D:\Downloads\Google-artsandculture-image-downlaod-master\Google-artsandculture-image-downlaod-master\async_tile_fetcher.py", line 42, in gather_progress
    total = await asyncio.gather(*[
  File "D:\Downloads\Google-artsandculture-image-downlaod-master\Google-artsandculture-image-downlaod-master\async_tile_fetcher.py", line 36, in print_percent
    res = await awaitable
  File "tile_fetch.py", line 101, in fetch_tile
    encrypted_bytes = await async_tile_fetcher.fetch(session, image_url, file_path)
  File "D:\Downloads\Google-artsandculture-image-downlaod-master\Google-artsandculture-image-downlaod-master\async_tile_fetcher.py", line 13, in modified
    raise err
Exception

**Comment by LuMitchell** [comment]
I used the proxy in my bash shell, can curl the "google.com"

**Comment by LuMitchell** [comment]
$ curl https://lh3.googleusercontent.com
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1561  100  1561    0     0   1210      0  0:00:01  0:00:01 --:--:--  1211<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 404 (Not Found)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>404.</b> <ins>That’s an error.</ins>
  <p>The requested URL <code>/</code> was not found on this server.  <ins>That’s all we know.</ins>

**Comment by LuMitchell** [comment]
> I set the proxy in async_tile_fetcher.py

```
async def fetch(session, url, destination):
    if destination.is_file():
        return destination.read_bytes()
    async with session.get(url,proxies = {
		"http": "http://127.0.0.1:1080",
		"https": "http://127.0.0.1:1080"
	}) as response:
        response.raise_for_status()
        file_bytes = await response.read()
        destination.write_bytes(file_bytes)
        return file_bytes
```

> still time out :(

Downloading image meta-information...
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\urllib\request.py", line 1319, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1004, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 944, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\http\client.py", line 915, in connect
    self.sock = self._create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 808, in create_connection
    raise err
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38-32\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError:

**Comment by LuMitchell** [comment]
I figure it out，just the proxy problem.
```
opener = urllib.request.build_opener(httpproxy_handler)
page_source = opener.open(url).read()
```
here I used the proxy, then I got the response

**Comment by MdSauravChowdhury** [comment]
sorry in that moment is email i am not using . you have mistake please
install all python packages. go to root directory and open your sell or
commend line. i hope 100% working . you have need any help please contact
me. my email address "mdsauravchowdhury@gmail.com"

pip install pycryptodome
pip install lxml
pip install Pillow
pip install aiohttp
